export const brandImages = {
  logo: "/images/logo.png",
  logoAlt: "Bb Salon SUITES — Hair & Braiding logo",
  banner: "/images/banner.jpg",
  bannerAlt: "Bb Salon SUITES — African hair braiding and salon suites in Columbus, OH",
  heroPortrait: "/images/hero-portrait.jpg",
  heroPortraitAlt: "Professional hair styling at Bb Salon SUITES — Columbus braiding salon",
} as const;

export const galleryBrandImages = [
  {
    id: "g1",
    src: "/images/gallery-braids-box.jpg",
    alt: "Box braids with gold cuffs at Bb Salon SUITES Columbus",
    category: "braids" as const,
    width: 800,
    height: 1000,
  },
  {
    id: "g2",
    src: "/images/gallery-glam-makeup.jpg",
    alt: "Full glam makeup and styled hair at Bb Salon SUITES",
    category: "makeup" as const,
    width: 800,
    height: 1000,
  },
  {
    id: "g3",
    src: "/images/gallery-cornrows.jpg",
    alt: "Elegant cornrow updo hairstyle at Bb Salon SUITES",
    category: "braids" as const,
    width: 800,
    height: 900,
  },
  {
    id: "g4",
    src: "/images/gallery-waves.jpg",
    alt: "Long silky waves and extensions at Bb Salon SUITES",
    category: "extensions" as const,
    width: 800,
    height: 1000,
  },
  {
    id: "g5",
    src: "/images/gallery-knotless.jpg",
    alt: "Knotless braids with laid edges at Bb Salon SUITES",
    category: "braids" as const,
    width: 800,
    height: 1000,
  },
  {
    id: "g6",
    src: "/images/gallery-locs.jpg",
    alt: "Goddess faux locs protective style at Bb Salon SUITES",
    category: "locs" as const,
    width: 800,
    height: 1000,
  },
  {
    id: "g7",
    src: "/images/gallery-boho-braids.jpg",
    alt: "Boho braids with curly ends at Bb Salon SUITES",
    category: "braids" as const,
    width: 800,
    height: 1000,
  },
  {
    id: "g8",
    src: "/images/suite-standard.jpg",
    alt: "Salon suite with pink walls, gold styling chair and arched LED mirror",
    category: "suites" as const,
    width: 800,
    height: 600,
  },
  {
    id: "g9",
    src: "/images/suite-window.jpg",
    alt: "Salon suite with arched LED mirror and black gold styling chair",
    category: "suites" as const,
    width: 800,
    height: 600,
  },
  {
    id: "g10",
    src: "/images/suite-premium.jpg",
    alt: "Premium salon suite with hexagonal LED ceiling and pink walls",
    category: "suites" as const,
    width: 800,
    height: 600,
  },
  {
    id: "g11",
    src: "/images/suite-station.jpg",
    alt: "Private styling station in Bb Salon SUITES Columbus",
    category: "suites" as const,
    width: 800,
    height: 600,
  },
  {
    id: "g12",
    src: "/images/suite-mirror.jpg",
    alt: "Full-length arched LED mirror in salon suite",
    category: "suites" as const,
    width: 800,
    height: 1000,
  },
  {
    id: "g13",
    src: "/images/suite-corner.jpg",
    alt: "Corner view of pink salon suite with gold chair",
    category: "suites" as const,
    width: 800,
    height: 600,
  },
] as const;

export const suiteImages = {
  standard: "/images/suite-standard.jpg",
  window: "/images/suite-window.jpg",
  premium: "/images/suite-premium.jpg",
  station: "/images/suite-station.jpg",
  mirror: "/images/suite-mirror.jpg",
  corner: "/images/suite-corner.jpg",
} as const;

export const suiteGalleryImages = [
  suiteImages.standard,
  suiteImages.window,
  suiteImages.premium,
  suiteImages.station,
  suiteImages.mirror,
  suiteImages.corner,
] as const;
