export const siteConfig = {
  name: "Bb Salon SUITES",
  tagline: "Your Beauty, Our Passion",
  subtitle: "Hair & Braiding",
  description:
    "Bb Salon SUITES offers expert hair braiding, lashes, eyebrows, makeup, and luxury salon suites for rent in Columbus, Ohio. Open daily 8AM–9:30PM. Services from $100. Suites $150/week.",
  url: "https://bbsalonsuites.com",
  locale: "en_US",
  phone: "(614) 622-4624",
  phoneRaw: "+16146224624",
  whatsapp: "13802655069",
  whatsappDisplay: "+1 (380) 265-5069",
  email: "bibichetg@gmail.com",
  owner: "Bibiche",
  promotion: "$20 OFF your first service",
  address: {
    street: "2177 E. Livingston Ave",
    city: "Columbus",
    state: "OH",
    zip: "43209",
    country: "US",
    full: "2177 E. Livingston Ave, Columbus, OH 43209",
    coordinates: {
      lat: 39.945,
      lng: -82.948,
    },
  },
  hours: [
    { day: "Monday", hours: "8:00 AM – 9:30 PM" },
    { day: "Tuesday", hours: "8:00 AM – 9:30 PM" },
    { day: "Wednesday", hours: "8:00 AM – 9:30 PM" },
    { day: "Thursday", hours: "8:00 AM – 9:30 PM" },
    { day: "Friday", hours: "8:00 AM – 9:30 PM" },
    { day: "Saturday", hours: "8:00 AM – 9:30 PM" },
    { day: "Sunday", hours: "8:00 AM – 9:30 PM" },
  ],
  hoursSummary: "Open Daily · 8:00 AM – 9:30 PM",
  social: {
    instagram: "https://instagram.com/bbsalonsuites",
    facebook: "https://facebook.com/bbsalonsuites",
    tiktok: "https://tiktok.com/@bbsalonsuites",
    google: "https://g.page/bbsalonsuites",
  },
  stats: {
    yearsInBusiness: 5,
    happyClients: 2000,
    professionals: 12,
    reviews: 350,
  },
  parking:
    "Free parking available on-site at our Livingston Avenue location. Only 7 minutes from downtown Columbus.",
  suitePriceWeekly: 150,
  servicesStartAt: 100,
} as const;

export const navigation = {
  main: [
    { name: "Home", href: "/" },
    { name: "About", href: "/about" },
    { name: "Services", href: "/services" },
    { name: "Gallery", href: "/gallery" },
    { name: "Team", href: "/team" },
    { name: "Book", href: "/book" },
    { name: "Suites", href: "/salon-suites" },
    { name: "Blog", href: "/blog" },
    { name: "Contact", href: "/contact" },
  ],
  services: [
    { name: "Knotless Braids", href: "/services/knotless-braids", description: "Lightweight, natural finish" },
    { name: "Box Braids", href: "/services/box-braids", description: "Classic protective style" },
    { name: "Boho Braids", href: "/services/boho-braids", description: "Bohemian braided look" },
    { name: "Cornrows", href: "/services/cornrows", description: "Intricate braided patterns" },
    { name: "Faux Locs", href: "/services/faux-locs", description: "Loc-style without commitment" },
    { name: "Twists", href: "/services/twists", description: "Senegalese & passion twists" },
    { name: "Hair Extensions", href: "/services/hair-extensions", description: "Length & volume" },
    { name: "Sew-Ins", href: "/services/sew-ins", description: "Secure weave installation" },
    { name: "Closures", href: "/services/closures", description: "Natural-looking closures" },
    { name: "Eyebrows", href: "/services/eyebrows", description: "Shaping & styling" },
    { name: "Lashes", href: "/services/lashes", description: "Extensions & lifts" },
    { name: "Makeup", href: "/services/makeup", description: "Glam & everyday looks" },
  ],
  footer: [
    { name: "About Us", href: "/about" },
    { name: "Services", href: "/services" },
    { name: "Gallery", href: "/gallery" },
    { name: "Meet the Team", href: "/team" },
    { name: "Book Appointment", href: "/book" },
    { name: "Salon Suites", href: "/salon-suites" },
    { name: "Testimonials", href: "/testimonials" },
    { name: "Blog", href: "/blog" },
    { name: "FAQ", href: "/faq" },
    { name: "Contact", href: "/contact" },
    { name: "Privacy Policy", href: "/privacy" },
    { name: "Terms of Service", href: "/terms" },
  ],
} as const;
