export const siteConfig = {
  name: "Lumière Beauty Studio",
  tagline: "Columbus's Premier Luxury Beauty Destination",
  description:
    "Lumière Beauty Studio offers luxury hair, color, nails, lashes, facials, and barber services in Columbus, Ohio. Book your appointment or rent a professional salon suite today.",
  url: "https://lumierebeautystudio.com",
  locale: "en_US",
  phone: "+1 (614) 555-0147",
  phoneRaw: "+16145550147",
  email: "hello@lumierebeautystudio.com",
  whatsapp: "16145550147",
  address: {
    street: "2450 Grandview Avenue",
    city: "Columbus",
    state: "OH",
    zip: "43212",
    country: "US",
    full: "2450 Grandview Avenue, Columbus, OH 43212",
    coordinates: {
      lat: 39.9897,
      lng: -83.0448,
    },
  },
  hours: [
    { day: "Monday", hours: "9:00 AM – 7:00 PM" },
    { day: "Tuesday", hours: "9:00 AM – 7:00 PM" },
    { day: "Wednesday", hours: "9:00 AM – 8:00 PM" },
    { day: "Thursday", hours: "9:00 AM – 8:00 PM" },
    { day: "Friday", hours: "9:00 AM – 8:00 PM" },
    { day: "Saturday", hours: "8:00 AM – 6:00 PM" },
    { day: "Sunday", hours: "10:00 AM – 4:00 PM" },
  ],
  social: {
    instagram: "https://instagram.com/lumierebeautystudio",
    facebook: "https://facebook.com/lumierebeautystudio",
    tiktok: "https://tiktok.com/@lumierebeautystudio",
    google: "https://g.page/lumierebeautystudio",
  },
  stats: {
    yearsInBusiness: 12,
    happyClients: 15000,
    professionals: 28,
    reviews: 2400,
  },
  parking:
    "Complimentary parking available in our private lot behind the building. Street parking also available on Grandview Avenue.",
} as const;

export const navigation = {
  main: [
    { name: "Home", href: "/" },
    { name: "About", href: "/about" },
    { name: "Services", href: "/services" },
    { name: "Gallery", href: "/gallery" },
    { name: "Team", href: "/team" },
    { name: "Book", href: "/book" },
    { name: "Suites", href: "/salon-suites" },
    { name: "Blog", href: "/blog" },
    { name: "Contact", href: "/contact" },
  ],
  services: [
    { name: "Hair Styling", href: "/services/hair-styling", description: "Cuts, blowouts & styling" },
    { name: "Hair Color", href: "/services/hair-color", description: "Full color & highlights" },
    { name: "Balayage", href: "/services/balayage", description: "Hand-painted highlights" },
    { name: "Braids", href: "/services/braids", description: "Protective & creative styles" },
    { name: "Extensions", href: "/services/extensions", description: "Length & volume solutions" },
    { name: "Barber", href: "/services/barber", description: "Men's grooming & fades" },
    { name: "Nails", href: "/services/nails", description: "Manicures & nail art" },
    { name: "Lashes", href: "/services/lashes", description: "Extensions & lifts" },
    { name: "Facials", href: "/services/facials", description: "Skincare treatments" },
  ],
  footer: [
    { name: "About Us", href: "/about" },
    { name: "Services", href: "/services" },
    { name: "Gallery", href: "/gallery" },
    { name: "Meet the Team", href: "/team" },
    { name: "Book Appointment", href: "/book" },
    { name: "Salon Suites", href: "/salon-suites" },
    { name: "Testimonials", href: "/testimonials" },
    { name: "Blog", href: "/blog" },
    { name: "FAQ", href: "/faq" },
    { name: "Contact", href: "/contact" },
    { name: "Privacy Policy", href: "/privacy" },
    { name: "Terms of Service", href: "/terms" },
  ],
} as const;
